import test from 'node:test';
import assert from 'node:assert/strict';
import { Timestamp } from 'firebase-admin/firestore';
import { validateInvitation, invitationHash } from '../src/worker-access.js';
import { cairoAppointmentMillis, reminderEligible, reminderVersion } from '../src/worker-reminders.js';
import { AI_TOOL_ALLOWLIST, validateAiPlan, aiAgentHandlers } from '../src/ai-agent.js';
const invite = () => ({status:'NEW',expiresAt:Timestamp.fromMillis(Date.now()+60000),phone:'01012345678',email:'worker@example.com'});
const identity = {phoneNumber:'+201012345678',email:'worker@example.com',emailVerified:true};
test('invitation accepts verified canonical phone and Google identity',()=>assert.doesNotThrow(()=>validateInvitation(invite(),identity)));
test('invitation cannot use unverified email',()=>assert.throws(()=>validateInvitation(invite(),{...identity,emailVerified:false})));
test('invitation rejects fake authenticated phone',()=>assert.throws(()=>validateInvitation(invite(),{...identity,phoneNumber:'+201012345679'})));
test('invalid invitation rejected',()=>assert.throws(()=>validateInvitation(null,identity)));
test('expired invitation rejected',()=>assert.throws(()=>validateInvitation({...invite(),expiresAt:Timestamp.fromMillis(0)},identity)));
test('single-use invitation rejected after redemption',()=>assert.throws(()=>validateInvitation({...invite(),status:'REDEEMED'},identity)));
test('hash retains no plaintext secret',()=>{assert.equal(invitationHash('a').length,64);assert.notEqual(invitationHash('a'),invitationHash('b'));});
test('Cairo winter appointment uses UTC+2',()=>assert.equal(new Date(cairoAppointmentMillis('2026-01-05','19:30')).toISOString(),'2026-01-05T17:30:00.000Z'));
test('Cairo summer appointment uses UTC+3',()=>assert.equal(new Date(cairoAppointmentMillis('2026-07-05','19:30')).toISOString(),'2026-07-05T16:30:00.000Z'));
const booking={branchId:'talkha',staffId:'worker-one',bookingDate:'2026-12-01',bookingTime:'19:00',status:'confirmed'};
test('15 minute reminder eligible future assigned booking',()=>assert.equal(reminderEligible(booking,0),true));
for(const status of ['cancelled','rejected','completed'])test(`${status} reminder suppressed`,()=>assert.equal(reminderEligible({...booking,status},0),false));
test('unassigned reminder suppressed',()=>assert.equal(reminderEligible({...booking,staffId:'any'},0),false));
test('expired appointment suppressed',()=>assert.equal(reminderEligible(booking,Date.parse('2027-01-01')),false));
test('rescheduling changes reminder identity',()=>assert.notEqual(reminderVersion(booking),reminderVersion({...booking,bookingTime:'20:00'})));
test('price change preserves reminder identity',()=>assert.equal(reminderVersion(booking),reminderVersion({...booking,total:500})));
test('AI allowlist contains no confirmation or collection access tool',()=>{assert.ok(AI_TOOL_ALLOWLIST.every(t=>!/^confirm/.test(t)));assert.throws(()=>validateAiPlan({tool:'queryFirestore',args:{}}));});
for(const key of ['role','branchIds','price','customerId','phone','url','collection','permissions'])test(`AI tool injection rejects ${key}`,()=>assert.throws(()=>validateAiPlan({tool:'prepareBooking',args:{[key]:'attacker'}})));
test('AI confirm tool forbidden to model',()=>assert.throws(()=>validateAiPlan({tool:'confirmBooking',args:{}})));
test('AI nested price injection rejected',()=>assert.throws(()=>validateAiPlan({tool:'prepareBooking',args:{items:[{id:'service',kind:'service',price:1}]}})));
test('AI valid availability plan accepted',()=>assert.equal(validateAiPlan({tool:'getAvailableSlots',args:{branchId:'talkha',bookingDate:'2026-12-01',items:[{id:'hair',kind:'service'}]}}).tool,'getAvailableSlots'));
test('AI disabled returns deterministic FAQ fallback without model or domain calls',async()=>{
 const h=aiAgentHandlers({db:{doc:()=>({get:async()=>({data:()=>({aiAgentEnabled:false})})})},apiKey:()=>{throw Error('must not read secret')},rateLimit:()=>{throw Error('must not call')}});
 assert.deepEqual(await h.agent({data:{message:'hello'}}),{fallback:true});assert.deepEqual(await h.confirm({data:{}}),{fallback:true});
});
