const qaExecutablePath=process.env.CHROMIUM_EXECUTABLE_PATH || await chromium.executablePath();
import {createServer} from 'vite';
import chromium from '@sparticuz/chromium';
import {chromium as playwright} from 'playwright';
import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url).pathname,out=new URL('../qa-evidence',import.meta.url).pathname;
const server=await createServer({root,server:{host:'127.0.0.1',port:4176,strictPort:true}});await server.listen();
await fs.mkdir(out,{recursive:true});
const apiSource=await fs.readFile(`${root}/src/admin-api.js`,'utf8');
const names=[...apiSource.matchAll(/export (?:async )?(?:function|const) (\w+)/g)].map(m=>m[1]);
const staff={id:'fixture-worker',nameAr:'عامل معاينة',branchIds:['talkha'],specialtyAr:'قص الشعر والعناية بالذقن',shiftStart:'11:00',shiftEnd:'23:00',imageUrl:'/assets/el-mezaen-mark-v2.webp',active:true};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const workspace={dateKey:today,staff,attendance:{status:'PRESENT',branchId:'talkha',checkInTime:'11:02',locationEvidence:{distanceMeters:23}},bookings:[{id:'fixture-booking',code:'MZ-TAL-FIXTURE',bookingDate:today,bookingTime:'19:30',customerName:'عميل اختبار',serviceNamesAr:['حلاقة شعر'],branchId:'talkha',status:'confirmed'}],tasks:[{id:'fixture-task',title:'تجهيز مكان العميل القادم',details:'بيانات اختبار للمعاينة',assigneeStaffId:staff.id,assigneeNameAr:staff.nameAr,branchId:'talkha',status:'NEW',priority:'normal'}],notifications:[{id:'fixture-note',staffId:staff.id,branchId:'talkha',type:'booking',entityId:'fixture-booking',title:'عندك حجز بعد 15 دقيقة',body:'بيانات اختبار للمعاينة',read:false}],target:{month:'2026-10',target:10000,achieved:4000,remaining:6000,progressPercent:40}};
const user={id:'fixture-worker-uid',name:'عامل معاينة',email:'fixture@example.test',role:'worker',branchIds:['talkha'],staffId:staff.id,permissions:['attendance','tasks'],active:true,accountStatus:'ACTIVE',authProviders:['google.com'],lastSignInAt:'2026-10-05T10:00:00Z'};
const launch=()=>playwright.launch({executablePath:qaExecutablePath,args:chromium.args.filter(a=>!a.startsWith('--use-gl')&&!a.startsWith('--use-angle')&&!a.includes('gpu')).concat(['--disable-gpu']),headless:true});
async function isolatedRole(role){const browser=await launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/firebase-config.js',r=>r.fulfill({contentType:'text/javascript',body:'window.__FIREBASE_CONFIG__={};'}));
await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());
await page.route('**/src/admin-api.js*',async r=>{
 const special={configured:'true',watchAuth:role==='none'?'callback => {queueMicrotask(()=>callback(null));return ()=>{};}':`callback => {queueMicrotask(()=>callback({uid:'fixture-uid',displayName:'حساب معاينة',email:'fixture@example.test',providerData:[{providerId:'google.com'}]}));return ()=>{};}`,currentRole:`async()=>(${JSON.stringify(role==='pending'||role==='none'?null:role)})`,requestWorkerAccess:`async()=>({status:'PENDING'})`,currentAccess:role==='appcheck'?`async()=>{throw Object.assign(new Error('App Check غير مصرح لهذه البيئة المحلية. سجّل Debug Token وأعد المحاولة.'),{code:'app-check/unavailable'});}`:`async()=>({role:${JSON.stringify(role)},staffId:'fixture-worker',branchIds:['talkha'],permissions:${JSON.stringify(role==='worker'?['attendance','tasks']:['dashboard','pos','bookings','revenue','attendance','tasks'])}})`,getWorkerWorkspace:`async()=>(${JSON.stringify(workspace)})`,getDashboard:`async()=>({bookings:[],ledger:[],expenses:[],stats:{bookingsToday:0,revenueToday:0}})`,getCollection:`async(collection)=>({items:collection==='staff'?[${JSON.stringify(staff)}]:collection==='users'?[${JSON.stringify(user)}]:[]})`,getAccessAccountCenter:`async()=>({staff:${JSON.stringify([user,{...user,id:'fixture-pending',name:'عامل في انتظار التفعيل — معاينة',accountStatus:'PENDING',staffId:null},{...user,id:'fixture-disabled',name:'حساب معطل — معاينة',accountStatus:'DISABLED',active:false}])},customers:[{id:'customer-uid',name:'عميل معاينة',phone:'01000000000',active:true,bookingCount:3}]})`,watchWorkerPush:'async()=>()=>{}'};
 const body=[...new Set(names)].map(n=>`export const ${n}=${special[n] || 'async()=>({})'};`).join('\n');await r.fulfill({contentType:'text/javascript',body});
});
await page.route('**/src/ai-chat.js*',async r=>{let source='import.meta.env={DEV:false};\n'+await fs.readFile(`${root}/src/ai-chat.js`,'utf8');source=source.replace("'./firebase-client.js'","'./qa-agent-client.js'");await r.fulfill({contentType:'text/javascript',body:source});});
await page.route('**/src/qa-agent-client.js',r=>r.fulfill({contentType:'text/javascript',body:`export const askCustomerAgent=async data=>data.message.includes('متاح')?({message:'مواعيد متاحة — بيانات اختبار',cards:[{nameAr:'عامل اختبار',specialtyAr:'قص الشعر'}],slots:['19:00','19:30','20:00']}):({message:'راجع حجز المعاينة قبل التأكيد',confirmation:{branchNameAr:'طلخا',serviceNamesAr:['حلاقة شعر — معاينة'],staffNameAr:'عامل اختبار',bookingDate:'2026-10-10',bookingTime:'19:30',subtotal:60,discountAmount:0,total:60},draftId:'${'a'.repeat(40)}',action:'prepareBooking'});export const confirmCustomerAgent=async()=>({ok:true});`}));
await page.addInitScript(()=>{localStorage.setItem('mz-branch','talkha');localStorage.setItem('mz-theme','dark');});
return {browser,page,errors,role};}
const checks=[];const base='http://127.0.0.1:4176';
const publicEnv=await isolatedRole('none');const {page}=publicEnv;
await page.setViewportSize({width:1440,height:900});await page.goto(base+'/');await page.locator('#branchQuickGrid .branch-quick-card').first().waitFor();
const branchImages=await page.locator('#branchQuickGrid img').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('src')));if(new Set(branchImages).size!==2)throw Error('Branch assets are not distinct');await page.locator('#branchQuickGrid').screenshot({path:out+'/Branch-Choice-Desktop.png'});checks.push({case:'branch distinct images',images:branchImages});
await page.setViewportSize({width:390,height:844});await page.locator('#branchQuickGrid').screenshot({path:out+'/Branch-Choice-Mobile.png'});await page.locator('#mobileQuickActions').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/Mobile-Footer-Contact-390.png'});
for(const id of ['talkha','mashaya']){await page.goto(base+`/branches/${id}/`);await page.locator('#branchTeam .team-card').first().waitFor();await page.screenshot({path:out+`/Branch-${id}-390.png`});await page.locator('#branchTeam').screenshot({path:out+`/Branch-${id}-Team-390.png`});const image=await page.locator('.branch-landing-photo').getAttribute('src');if(!image.includes('branch-'+id))throw Error('Wrong branch detail image');checks.push({case:'branch detail',id,image,fixtureOnly:true});}
for(const route of ['services','packages','team','branches/talkha']){await page.goto(base+'/'+route+'/');if(!await page.locator('[data-safe-back]').isVisible())throw Error('Back control missing');await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.locator('.scroll-top').waitFor({state:'visible'});await page.screenshot({path:out+'/Back-Top-'+route.replaceAll('/','-')+'-390.png'});await page.locator('.scroll-top').click();await page.waitForFunction(()=>scrollY<2);checks.push({case:'back-top',route,passed:true});}
await page.route('**/src/qa-agent-client.js',r=>r.fulfill({contentType:'text/javascript',body:`import {seedCatalog} from '/src/seed-data.js';import {createDevConversation} from '/src/ai-dev-provider.js';export const askCustomerAgent=createDevConversation(seedCatalog);export const confirmCustomerAgent=async()=>{throw Error('DEV fixture writes prohibited');};`}));
await page.goto(base+'/');await page.locator('.faq-chat-fab').click();await page.locator('.ai-welcome').waitFor();if(await page.locator('.ai-panel').innerText().then(t=>/FAQ|اختار سؤال/.test(t)))throw Error('Visible FAQ identity');await page.evaluate(()=>{const badge=document.createElement('small');badge.className='ai-dev-indicator';badge.textContent='DEV • محادثة وبيانات اختبار';document.querySelector('.ai-panel header').append(badge)});await page.screenshot({path:out+'/AI-Welcome-390.png'});
async function say(message){const before=await page.locator('.ai-message.assistant').count();await page.locator('.ai-panel input[name=message]').fill(message);await page.locator('.ai-panel form').evaluate(f=>f.requestSubmit());await page.waitForFunction(n=>document.querySelectorAll('.ai-message.assistant').length>n,before);checks.push({case:'free text',message,reply:await page.locator('.ai-message.assistant').last().textContent(),fixtureOnly:true});}
await say('السلام عليكم');await page.screenshot({path:out+'/AI-Free-Text-390.png'});await say('عاوز طلخا');await say('انا عاوز اعمل حاجة في شعري ومش عارف ايه المناسب');await page.locator('.ai-action-card button').filter({hasText:'اختار الخدمة'}).first().waitFor();await page.locator('[data-card-type=service]').first().scrollIntoViewIfNeeded();await page.screenshot({path:out+'/AI-Service-Recommendation-390.png'});await page.locator('.ai-action-card button').filter({hasText:'اختار الخدمة'}).first().click();await page.locator('.ai-action-card button').filter({hasText:/اختار (?!الخدمة)/}).first().waitFor();await page.locator('[data-card-type=worker]').first().waitFor();await page.locator('[data-card-type=worker]').first().scrollIntoViewIfNeeded();await page.screenshot({path:out+'/AI-Worker-Recommendation-390.png'});await page.locator('.ai-action-card button').filter({hasText:/اختار (?!الخدمة)/}).first().click();await say('بكرة بعد ٧');await page.locator('.ai-slots button').first().waitFor();await page.screenshot({path:out+'/AI-Slots-390.png'});await page.locator('.ai-slots button').first().click();await page.locator('.ai-action-card.confirmation').waitFor();await page.screenshot({path:out+'/AI-Booking-Confirmation-DEV-390.png'});
await publicEnv.browser.close();
for(const route of ['/admin','/admin/']){const env=await isolatedRole('appcheck');await env.page.setViewportSize({width:1440,height:900});await env.page.goto(base+route);await env.page.locator('.branded-auth-error').waitFor();await env.page.getByText('تعذر فتح لوحة الإدارة محليًا',{exact:true}).waitFor();if(env.page.url().includes('/login'))throw Error('App Check error redirected');await env.page.locator('.local-appcheck-setup summary').click();await env.page.screenshot({path:out+(route.endsWith('/')?'/Admin-Local-Slash.png':'/Admin-Local-NoSlash.png')});checks.push({case:'local admin App Check',route,canonical:env.page.url(),passed:true});await env.browser.close();}
await fs.writeFile(out+'/phase113-closure-results.json',JSON.stringify({checks,fixtureOnly:true},null,2));console.log(JSON.stringify({checks:checks.length,failures:0}));await server.close();
