const qaExecutablePath=process.env.CHROMIUM_EXECUTABLE_PATH || await chromium.executablePath();
import {createServer} from 'vite';
import chromium from '@sparticuz/chromium';
import {chromium as playwright} from 'playwright';
import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url).pathname,out=new URL('../qa-evidence',import.meta.url).pathname;
const server=await createServer({root,server:{host:'127.0.0.1',port:4175,strictPort:true}});await server.listen();
await fs.mkdir(out,{recursive:true});
const apiSource=await fs.readFile(`${root}/src/admin-api.js`,'utf8');
const names=[...apiSource.matchAll(/export (?:async )?(?:function|const) (\w+)/g)].map(m=>m[1]);
const staff={id:'fixture-worker',nameAr:'عامل معاينة',branchIds:['talkha'],specialtyAr:'قص الشعر والعناية بالذقن',shiftStart:'11:00',shiftEnd:'23:00',imageUrl:'/assets/el-mezaen-mark-v2.webp',active:true};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
const workspace={dateKey:today,staff,attendance:{status:'PRESENT',branchId:'talkha',checkInTime:'11:02',locationEvidence:{distanceMeters:23}},bookings:[{id:'fixture-booking',code:'MZ-TAL-FIXTURE',bookingDate:today,bookingTime:'19:30',customerName:'عميل اختبار',serviceNamesAr:['حلاقة شعر'],branchId:'talkha',status:'confirmed'}],tasks:[{id:'fixture-task',title:'تجهيز مكان العميل القادم',details:'بيانات اختبار للمعاينة',assigneeStaffId:staff.id,assigneeNameAr:staff.nameAr,branchId:'talkha',status:'NEW',priority:'normal'}],notifications:[{id:'fixture-note',staffId:staff.id,branchId:'talkha',type:'booking',entityId:'fixture-booking',title:'عندك حجز بعد 15 دقيقة',body:'بيانات اختبار للمعاينة',read:false}],target:{month:'2026-10',target:10000,achieved:4000,remaining:6000,progressPercent:40}};
const user={id:'fixture-worker-uid',name:'عامل معاينة',email:'fixture@example.test',role:'worker',branchIds:['talkha'],staffId:staff.id,permissions:['attendance','tasks'],active:true,accountStatus:'ACTIVE',authProviders:['google.com'],lastSignInAt:'2026-10-05T10:00:00Z'};
const launch=()=>playwright.launch({executablePath:qaExecutablePath,args:chromium.args.filter(a=>!a.startsWith('--use-gl')&&!a.startsWith('--use-angle')&&!a.includes('gpu')).concat(['--disable-gpu']),headless:true});
async function isolatedRole(role){const browser=await launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/firebase-config.js',r=>r.fulfill({contentType:'text/javascript',body:'window.__FIREBASE_CONFIG__={};'}));
await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());
await page.route('**/src/admin-api.js*',async r=>{
 const special={configured:'true',watchAuth:role==='none'?'callback => {queueMicrotask(()=>callback(null));return ()=>{};}':`callback => {queueMicrotask(()=>callback({uid:'fixture-uid',displayName:'حساب معاينة',email:'fixture@example.test',providerData:[{providerId:'google.com'}]}));return ()=>{};}`,currentRole:`async()=>(${JSON.stringify(role==='pending'||role==='none'?null:role)})`,requestWorkerAccess:`async()=>({status:'PENDING'})`,currentAccess:`async()=>({role:${JSON.stringify(role)},staffId:'fixture-worker',branchIds:['talkha'],permissions:${JSON.stringify(role==='worker'?['attendance','tasks']:['dashboard','pos','bookings','revenue','attendance','tasks'])}})`,getWorkerWorkspace:`async()=>(${JSON.stringify(workspace)})`,getDashboard:`async()=>({bookings:[],ledger:[],expenses:[],stats:{bookingsToday:0,revenueToday:0}})`,getCollection:`async(collection)=>({items:collection==='staff'?[${JSON.stringify(staff)}]:collection==='users'?[${JSON.stringify(user)}]:[]})`,getAccessAccountCenter:`async()=>({staff:${JSON.stringify([user,{...user,id:'fixture-pending',name:'عامل في انتظار التفعيل — معاينة',accountStatus:'PENDING',staffId:null},{...user,id:'fixture-disabled',name:'حساب معطل — معاينة',accountStatus:'DISABLED',active:false}])},customers:[{id:'customer-uid',name:'عميل معاينة',phone:'01000000000',active:true,bookingCount:3}]})`,watchWorkerPush:'async()=>()=>{}'};
 const body=[...new Set(names)].map(n=>`export const ${n}=${special[n] || 'async()=>({})'};`).join('\n');await r.fulfill({contentType:'text/javascript',body});
});
await page.route('**/src/ai-chat.js*',async r=>{let source='import.meta.env={DEV:false};\n'+await fs.readFile(`${root}/src/ai-chat.js`,'utf8');source=source.replace("'./firebase-client.js'","'./qa-agent-client.js'");await r.fulfill({contentType:'text/javascript',body:source});});
await page.route('**/src/qa-agent-client.js',r=>r.fulfill({contentType:'text/javascript',body:`export const askCustomerAgent=async data=>data.message.includes('متاح')?({message:'مواعيد متاحة — بيانات اختبار',cards:[{nameAr:'عامل اختبار',specialtyAr:'قص الشعر'}],slots:['19:00','19:30','20:00']}):({message:'راجع حجز المعاينة قبل التأكيد',confirmation:{branchNameAr:'طلخا',serviceNamesAr:['حلاقة شعر — معاينة'],staffNameAr:'عامل اختبار',bookingDate:'2026-10-10',bookingTime:'19:30',subtotal:60,discountAmount:0,total:60},draftId:'${'a'.repeat(40)}',action:'prepareBooking'});export const confirmCustomerAgent=async()=>({ok:true});`}));
await page.addInitScript(()=>{localStorage.setItem('mz-branch','talkha');localStorage.setItem('mz-theme','dark');});
return {browser,page,errors,role};}
const sizes=[[320,568],[360,800],[375,812],[390,844],[412,915],[430,932],[768,1024],[820,1180],[1024,768],[1280,720],[1440,900],[1920,1080]];
const results=[],proofs=[];
async function layout(page,role,width,errors){const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow||errors.length)throw Error(JSON.stringify({role,width,overflow,errors}));results.push({role,width,overflow,errors:[...errors]});}
for(const role of ['worker','admin','manager','cashier']){const env=await isolatedRole(role),{page,errors}=env;
 for(const [width,height]of sizes){await page.setViewportSize({width,height});const route=role==='worker'?'/worker/':`/admin/?qa=${role}-${width}#admin=${role==='cashier'?'calendar':'dashboard'}`;await page.goto('http://127.0.0.1:4175'+route);
 if(role==='worker'){await page.locator('#workspace').waitFor({state:'visible'});if(!page.url().includes('/worker/'))throw Error('Wrong Worker route');await page.locator('#name').filter({hasText:'عامل معاينة'}).waitFor();for(const screen of ['home','attendance','bookings','tasks','notifications','profile']){await page.locator(`${screen==='notifications'?'.worker-header':'.worker-nav'} [data-view="${screen}"]`).click();await page.locator(`[data-screen="${screen}"]`).waitFor({state:'visible'});if([390,768,1440].includes(width))await page.screenshot({path:`${out}/Worker-${screen}-${width}.png`});}}
 else{await page.waitForFunction(r=>document.documentElement.dataset.adminRole===r,role);const roleSelector=role==='cashier'?'#cashierHeader .cashier-role-badge':'#visualRoleBadge';await page.locator(roleSelector).waitFor({state:'visible'});const label=({admin:'أدمن',manager:'مدير',cashier:'كاشير'})[role];if((await page.locator(role==='cashier'?'#cashierHeader .cashier-role-badge':'#visualRoleBadge').textContent())!==label)throw Error('Role mismatch');if([390,768,1440].includes(width))await page.screenshot({path:`${out}/${role}-Dashboard-${width}.png`});}
 await layout(page,role,width,errors);proofs.push({role,width,url:page.url(),visibleRole:role==='worker'?'عامل معاينة':await page.locator(role==='cashier'?'#cashierHeader .cashier-role-badge':'#visualRoleBadge').textContent(),isolatedBrowser:true});
 if(role==='admin'&&[390,768,1440].includes(width)){await page.goto(`http://127.0.0.1:4175/admin/?qa=accounts-${width}#admin=users`);await page.waitForFunction(()=>document.querySelector('#users')?.classList.contains('active'));await page.locator('#users h1').filter({hasText:'مركز إدارة الحسابات'}).waitFor({state:'visible'});await page.locator('#userAccountsList .user-access-card').first().waitFor({state:'visible'});for(const selector of ['.account-category-tabs','#accountStatusFilter','#accountBranchFilter','#accountSearch'])if(!await page.locator(selector).isVisible())throw Error('Missing account controls '+selector);await page.screenshot({path:`${out}/Admin-Account-Center-${width}.png`});await page.screenshot({path:`${out}/Admin-Account-Center-${width}-FULL.png`,fullPage:true});proofs.push({role:'admin-account-center',width,usersActive:true,headingVisible:true,controlsVisible:true,isolatedBrowser:true});await layout(page,'admin-account-center',width,errors);}
 }await env.browser.close();}
const ai=await isolatedRole('none');for(const[width,height]of sizes){const {page,errors}=ai;await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:4175/');await page.evaluate(async()=>{const {openAiChat}=await import('/src/ai-chat.js');openAiChat({branch:{id:'talkha',nameAr:'فرع طلخا'},faqs:[],lang:'ar'});});await page.locator('.ai-welcome').waitFor({state:'visible'});if([390,768,1440].includes(width))await page.screenshot({path:`${out}/AI-Agent-${width}.png`});await page.locator('.ai-panel input[name=message]').fill('مين متاح؟');await page.locator('.ai-panel form').evaluate(f=>f.requestSubmit());await page.locator('.ai-slots button').first().waitFor();if(width===390)await page.screenshot({path:`${out}/AI-Availability-${width}.png`});await page.locator('.ai-panel input[name=message]').fill('احجزلي الساعة 7:30');await page.locator('.ai-panel form').evaluate(f=>f.requestSubmit());await page.locator('.ai-action-card.confirmation').waitFor();if([390,768,1440].includes(width))await page.screenshot({path:`${out}/AI-Booking-Confirmation-${width}.png`});await layout(page,'ai-preview',width,errors);}await ai.browser.close();
for(const role of ['none','pending']){const env=await isolatedRole(role),{page}=env;await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4175/login/'+(role==='pending'?'?mode=worker':''));if(role==='pending'){await page.locator('#pendingActivation').waitFor({state:'visible'});await page.screenshot({path:`${out}/Login-Pending-390.png`});}else{await page.locator('#loginForm').waitFor({state:'visible'});await page.screenshot({path:`${out}/Login-Staff-390.png`});await page.locator('[data-login-mode="worker"]').click();await page.locator('#workerPhoneForm').waitFor({state:'visible'});await page.screenshot({path:`${out}/Login-Worker-Phone-390.png`});await page.locator('#workerGoogle').focus();await page.screenshot({path:`${out}/Login-Worker-Google-390.png`});}await env.browser.close();}
const routingResults=[];
for(const [role,path,expected]of [['worker','/admin/','/worker/'],['admin','/worker/','/admin/'],['manager','/worker/','/admin/'],['cashier','/worker/','/admin/'],['none','/worker/','/login/?mode=worker']]){const env=await isolatedRole(role);await env.page.goto('http://127.0.0.1:4175'+path);await env.page.waitForURL(url=>url.pathname+url.search===expected||url.pathname===expected);routingResults.push({role,path,url:env.page.url(),passed:true,isolatedBrowser:true});await env.browser.close();}
await fs.writeFile(`${out}/workspace-results.json`,JSON.stringify({fixtureOnly:true,results,proofs},null,2));await fs.writeFile(`${out}/route-role-browser.json`,JSON.stringify({fixtureOnly:true,routing:routingResults},null,2));console.log(JSON.stringify({checks:results.length,proofs:proofs.length,roleRedirects:routingResults.length,failures:0}));await server.close();
