import { renderPublicPage, renderAdminPage, renderLoginPage, manifest, serviceWorker } from "./templates.js";

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const html=(body,status=200)=>new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-cache"}});
let ready=false;
const defaults={
 services:[
  ['hair-cut','الشعر','Hair','قص شعر','Haircut',30,100],['hair-style','الشعر','Hair','استشوار وتصفيف','Blow-dry & styling',25,100],['hair-curly','الشعر','Hair','كيرلي','Curly styling',30,150],
  ['beard-trim','الذقن','Beard','تحديد وتهذيب الذقن','Beard trim',20,70],['beard-color','دقن','Beard care','صبغة دقن','Beard coloring',30,120],
  ['skin-clean','البشرة','Skin','تنظيف بشرة','Facial cleansing',45,250],['skin-deep','تنضيف بشره','Facial cleansing','تنظيف بشرة عميق','Deep facial cleansing',60,350],['skin-mask','البشرة','Skin','ماسك عناية بالبشرة','Skin care mask',25,120],
  ['wax-face','شمع','Wax','شمع للوجه','Face waxing',15,60],['wax-nose','شمع','Wax','شمع الأنف والأذن','Nose & ear waxing',15,70],
  ['care-protein','عنايه بالشعر','Hair care','بروتين الشعر','Hair protein',90,700],['care-cream','عنايه بالشعر','Hair care','حمام كريم','Hair cream bath',30,150],
  ['service-wash','سيرفيس','Service','غسيل وتصفيف','Wash & style',20,80],['service-vip','سيرفيس','Service','سيرفيس VIP','VIP service',30,150],
  ['install-hair','تركيب','Installation','تركيب شعر','Hair system installation',90,1000],['install-maint','تركيب','Installation','صيانة تركيب','Hair system maintenance',60,500],
  ['extra-blackmask','إضافات','Extras','بلاك ماسك','Black mask',20,100],['extra-color','إضافات','Extras','صبغة شعر','Hair coloring',45,300],
  ['product-wax','بضاعه','Products','واكس تصفيف','Styling wax',5,150],['product-cream','بضاعه','Products','كريم عناية بالشعر','Hair care cream',5,180]
 ],
 packages:[
  ['pkg-complete-45','الباقه المتكامله','Complete Package','تجربة متكاملة للعناية بإطلالتك',45,350,1],['pkg-offer-200','عرض 200','EGP 200 Offer','عرض مميز لفترة محدودة',40,200,0],['pkg-basic','الباقه الاساسيه','Basic Package','الأساسيات للوك مرتب ونظيف',45,250,0],['pkg-youth','عرض الشباب','Youth Offer','خدمات سريعة وعصرية للشباب',30,150,1],['pkg-newyear','عرض راس السنه','New Year Offer','تجهيز كامل للمناسبات',60,550,0],['pkg-complete-60','الباقة المتكاملة','Complete Plus','الباقة المتكاملة بوقت أطول',60,400,1]
 ],
 staff:[['staff-any','أي حلاق متاح','Any available barber','متخصص مزين مصر','Muzain specialist','',1],['staff-ali','علي','Ali','قصات عصرية وتصفيف','Modern cuts & styling','https://control.muzain.com/storage/uploads/team_members/69343f5ca840a.jpg',1],['staff-fares','فارس','Fares','قصات وتحديد','Cuts & beard lines','https://control.muzain.com/storage/uploads/team_members/69343c60173e5.jpg',1],['staff-mahmoud','محمود عامر','Mahmoud Amer','عناية وتصفيف','Care & styling','https://control.muzain.com/storage/uploads/team_members/69343d55a81f5.jpg',1],['staff-sayed','السيد محمد','El Sayed Mohamed','قصات عصرية','Modern cuts','https://control.muzain.com/storage/uploads/team_members/69344a0b1af35.jpg',1],['staff-shawaf','الشواف','El Shawaf','ذقن وتصفيف','Beard & styling','https://control.muzain.com/storage/uploads/team_members/693448c5760c1.jpg',1]]
};

async function ensureDB(env){if(!env?.DB||ready)return;await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,items_json TEXT NOT NULL DEFAULT '[]',service_name TEXT NOT NULL DEFAULT '',staff_name TEXT NOT NULL,booking_date TEXT NOT NULL,booking_time TEXT NOT NULL,total REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',payment_status TEXT NOT NULL DEFAULT 'unpaid',paid_at TEXT,notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY,category TEXT NOT NULL,category_en TEXT NOT NULL DEFAULT '',name TEXT NOT NULL,name_en TEXT NOT NULL DEFAULT '',duration INTEGER NOT NULL,price REAL NOT NULL,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS packages(id TEXT PRIMARY KEY,name TEXT NOT NULL,name_en TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',duration INTEGER NOT NULL,price REAL NOT NULL,featured INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS staff(id TEXT PRIMARY KEY,name TEXT NOT NULL,name_en TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT '',role_en TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS content(id TEXT PRIMARY KEY,type TEXT NOT NULL,title TEXT NOT NULL,title_en TEXT NOT NULL DEFAULT '',body TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',link_url TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)`)
 ,env.DB.prepare(`CREATE TABLE IF NOT EXISTS coupons(code TEXT PRIMARY KEY,discount_percent REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`)
 ]);
 const migrations=["ALTER TABLE bookings ADD COLUMN items_json TEXT NOT NULL DEFAULT '[]'","ALTER TABLE bookings ADD COLUMN payment_status TEXT NOT NULL DEFAULT 'unpaid'","ALTER TABLE bookings ADD COLUMN paid_at TEXT","ALTER TABLE services ADD COLUMN category_en TEXT NOT NULL DEFAULT ''","ALTER TABLE services ADD COLUMN name_en TEXT NOT NULL DEFAULT ''","ALTER TABLE services ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0","ALTER TABLE packages ADD COLUMN name_en TEXT NOT NULL DEFAULT ''","ALTER TABLE packages ADD COLUMN duration INTEGER NOT NULL DEFAULT 45","ALTER TABLE packages ADD COLUMN active INTEGER NOT NULL DEFAULT 1","ALTER TABLE staff ADD COLUMN name_en TEXT NOT NULL DEFAULT ''","ALTER TABLE staff ADD COLUMN role_en TEXT NOT NULL DEFAULT ''"];
 for(const q of migrations)try{await env.DB.prepare(q).run()}catch{}
 let c=await env.DB.prepare('SELECT COUNT(*) c FROM services').first();if(!c?.c)await env.DB.batch(defaults.services.map((s,i)=>env.DB.prepare('INSERT INTO services(id,category,category_en,name,name_en,duration,price,active,sort_order) VALUES(?,?,?,?,?,?,?,1,?)').bind(...s,i)));
 c=await env.DB.prepare('SELECT COUNT(*) c FROM packages').first();if(!c?.c)await env.DB.batch(defaults.packages.map(s=>env.DB.prepare('INSERT INTO packages(id,name,name_en,description,duration,price,featured,active) VALUES(?,?,?,?,?,?,?,1)').bind(...s)));
 c=await env.DB.prepare('SELECT COUNT(*) c FROM staff').first();if(!c?.c)await env.DB.batch(defaults.staff.map(s=>env.DB.prepare('INSERT INTO staff(id,name,name_en,role,role_en,image_url,active) VALUES(?,?,?,?,?,?,?)').bind(...s)));
 await env.DB.batch([['phone','01093008896'],['hours','11:00–23:00'],['address','طلخا – الدقهلية'],['about','منذ 1995 ومزين مصر بيقدم تجربة حلاقة وعناية رجالية تهتم بأدق التفاصيل.'],['facebook','https://www.facebook.com/profile.php?id=61559147948668'],['instagram','https://www.instagram.com/ahmed_elmzin1'],['tiktok','https://www.tiktok.com/@ahmedelmzin1']].map(x=>env.DB.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').bind(...x)));
 await env.DB.prepare("INSERT OR IGNORE INTO coupons(code,discount_percent,active) VALUES('WELCOME10',10,1)").run();
 ready=true;
}
function cookie(req,name){return (`; ${req.headers.get('cookie')||''}`).split(`; ${name}=`).pop()?.split(';')[0]||''}
async function tokenFor(password,env){const data=new TextEncoder().encode(password+'|'+(env.ADMIN_SECRET||env.ADMIN_PASSWORD||'mz'));const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function isAdmin(req,env){const email=req.headers.get('oai-authenticated-user-email')?.trim().toLowerCase();if(email&&(!env.ADMIN_EMAIL||email===String(env.ADMIN_EMAIL).trim().toLowerCase()))return true;if(!env.ADMIN_PASSWORD)return false;return cookie(req,'mz_admin')===await tokenFor(env.ADMIN_PASSWORD,env)}
async function login(req,env){const body=await req.formData();if(!env.ADMIN_PASSWORD||body.get('password')!==env.ADMIN_PASSWORD)return html(renderLoginPage('كلمة المرور غير صحيحة'),401);const token=await tokenFor(env.ADMIN_PASSWORD,env);return new Response(null,{status:302,headers:{location:'/admin','set-cookie':`mz_admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`}})}
async function catalog(env,all=false){await ensureDB(env);if(!env.DB)return json({ok:true,services:defaults.services,packages:defaults.packages,staff:defaults.staff});const [s,p,t,c,settings]=await Promise.all([env.DB.prepare(`SELECT * FROM services ${all?'':'WHERE active=1'} ORDER BY sort_order,category,name`).all(),env.DB.prepare(`SELECT * FROM packages ${all?'':'WHERE active=1'} ORDER BY featured DESC,price`).all(),env.DB.prepare(`SELECT * FROM staff ${all?'':'WHERE active=1'} ORDER BY name`).all(),env.DB.prepare(`SELECT * FROM content ${all?'':'WHERE active=1'} ORDER BY created_at DESC`).all(),env.DB.prepare('SELECT key,value FROM settings').all()]);return json({ok:true,services:s.results,packages:p.results,staff:t.results,content:c.results,settings:Object.fromEntries((settings.results||[]).map(x=>[x.key,x.value]))})}
async function validateCoupon(env,code){if(!code)return 0;const row=await env.DB.prepare('SELECT discount_percent FROM coupons WHERE UPPER(code)=UPPER(?) AND active=1').bind(code.trim()).first();return Math.max(0,Math.min(100,Number(row?.discount_percent||0)))}
async function createBooking(req,env){const b=await req.json().catch(()=>null);const fullName=[b?.customer?.firstName,b?.customer?.lastName].filter(Boolean).join(' ').trim()||b?.customer?.name;if(!fullName||!b?.customer?.phone||!Array.isArray(b.items)||!b.items.length||!b.date||!b.time)return json({ok:false,message:'بيانات الحجز غير مكتملة'},400);await ensureDB(env);const code=`MZ-${Date.now().toString().slice(-7)}`,subtotal=b.items.reduce((n,x)=>n+Number(x.price||0),0),discountPercent=await validateCoupon(env,b.coupon),total=Math.max(0,subtotal-(subtotal*discountPercent/100)),names=b.items.map(x=>x.name).join(' + ');await env.DB.prepare(`INSERT INTO bookings(code,customer_name,phone,items_json,service_name,staff_name,booking_date,booking_time,total,status,payment_status,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,'pending','unpaid',?,datetime('now'))`).bind(code,fullName,b.customer.phone,JSON.stringify(b.items),names,b.staff||'أي عضو',b.date,b.time,total,b.customer.notes||'').run();return json({ok:true,bookingCode:code,subtotal,discountPercent,total})}
async function dashboard(env){await ensureDB(env);const [bookings,stats]=await Promise.all([env.DB.prepare('SELECT * FROM bookings ORDER BY created_at DESC LIMIT 500').all(),env.DB.prepare(`SELECT COUNT(*) bookings_count,SUM(CASE WHEN date(created_at)=date('now') THEN 1 ELSE 0 END) today_count,COALESCE(SUM(CASE WHEN payment_status='paid' THEN total ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN payment_status='paid' AND date(paid_at)=date('now') THEN total ELSE 0 END),0) today_revenue FROM bookings`).first()]);return json({ok:true,bookings:bookings.results,stats})}
async function updateBooking(req,env,code){const b=await req.json().catch(()=>null);await ensureDB(env);if(b.payment_status){if(!['unpaid','paid','refunded'].includes(b.payment_status))return json({ok:false},400);await env.DB.prepare(`UPDATE bookings SET payment_status=?,paid_at=CASE WHEN ?='paid' AND payment_status!='paid' THEN datetime('now') WHEN ?!='paid' THEN NULL ELSE paid_at END WHERE code=?`).bind(b.payment_status,b.payment_status,b.payment_status,code).run()}if(b.status){if(!['pending','confirmed','completed','cancelled'].includes(b.status))return json({ok:false},400);await env.DB.prepare('UPDATE bookings SET status=? WHERE code=?').bind(b.status,code).run()}return json({ok:true})}
const configs={services:{table:'services',fields:['category','category_en','name','name_en','duration','price','active','sort_order']},packages:{table:'packages',fields:['name','name_en','description','duration','price','featured','active']},staff:{table:'staff',fields:['name','name_en','role','role_en','image_url','active']},content:{table:'content',fields:['type','title','title_en','body','image_url','link_url','active']}};
async function saveEntity(req,env,type,id){const cfg=configs[type],b=await req.json().catch(()=>null);if(!cfg||!b)return json({ok:false},400);await ensureDB(env);id=id||`${type.slice(0,3)}-${crypto.randomUUID()}`;const vals=cfg.fields.map(f=>b[f]??(f==='active'?1:''));await env.DB.prepare(`INSERT INTO ${cfg.table}(id,${cfg.fields.join(',')}) VALUES(?,${cfg.fields.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${cfg.fields.map(f=>`${f}=excluded.${f}`).join(',')}`).bind(id,...vals).run();return json({ok:true,id})}
async function deleteEntity(env,type,id){const cfg=configs[type];if(!cfg)return json({ok:false},400);await ensureDB(env);await env.DB.prepare(`DELETE FROM ${cfg.table} WHERE id=?`).bind(id).run();return json({ok:true})}
async function saveSettings(req,env){const b=await req.json().catch(()=>null);await ensureDB(env);await env.DB.batch(Object.entries(b||{}).map(([k,v])=>env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,String(v))));return json({ok:true})}

export default{async fetch(req,env){const u=new URL(req.url),p=u.pathname;
 if(p==='/manifest.webmanifest')return new Response(manifest,{headers:{'content-type':'application/manifest+json'}});if(p==='/sw.js')return new Response(serviceWorker,{headers:{'content-type':'application/javascript','cache-control':'no-cache'}});
 if(p==='/api/catalog'&&req.method==='GET')return catalog(env);if(p==='/api/coupon'&&req.method==='POST'){await ensureDB(env);const b=await req.json().catch(()=>({})),discountPercent=await validateCoupon(env,b.code);return json({ok:discountPercent>0,discountPercent,message:discountPercent?'تم تطبيق الخصم':'كود الخصم غير صحيح'})}if(p==='/api/bookings'&&req.method==='POST')return createBooking(req,env);if(p==='/admin/login'&&req.method==='POST')return login(req,env);
 if(p.startsWith('/api/admin/')){if(!await isAdmin(req,env))return json({ok:false,message:'غير مصرح'},401);if(p==='/api/admin/dashboard')return dashboard(env);if(p==='/api/admin/catalog')return catalog(env,true);if(p==='/api/admin/settings'&&req.method==='PUT')return saveSettings(req,env);const bm=p.match(/^\/api\/admin\/bookings\/([^/]+)$/);if(bm&&req.method==='PATCH')return updateBooking(req,env,decodeURIComponent(bm[1]));const m=p.match(/^\/api\/admin\/(services|packages|staff|content)(?:\/([^/]+))?$/);if(m&&['POST','PUT'].includes(req.method))return saveEntity(req,env,m[1],m[2]&&decodeURIComponent(m[2]));if(m&&req.method==='DELETE'&&m[2])return deleteEntity(env,m[1],decodeURIComponent(m[2]));}
 if(p==='/admin'||p.startsWith('/admin/')){if(!await isAdmin(req,env))return html(renderLoginPage());return html(renderAdminPage())}if(p==='/'||p==='/booking')return html(renderPublicPage());if(p==='/robots.txt')return new Response('User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: https://el-mezaen-booking.basemngm.chatgpt.site/sitemap.xml');if(p==='/sitemap.xml')return new Response(`<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://el-mezaen-booking.basemngm.chatgpt.site/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url></urlset>`,{headers:{'content-type':'application/xml'}});return new Response('Not found',{status:404})}};
