import "./account.css";
import "./account-favorite.css";
import { initializeApp } from "firebase/app";
import { initializeAppCheck, ReCaptchaEnterpriseProvider } from "firebase/app-check";
import { browserLocalPersistence, getAuth, onAuthStateChanged, RecaptchaVerifier, setPersistence, signInWithPhoneNumber, signOut } from "firebase/auth";
import { getFunctions, httpsCallable } from "firebase/functions";
import QRCode from "qrcode";
import { bindSafeBack } from "./navigation.js";

bindSafeBack();

const config=globalThis.__FIREBASE_CONFIG__||{};const configured=Boolean(config.projectId&&!String(config.projectId).includes("YOUR_"));
const $=selector=>document.querySelector(selector);let confirmation=null;let portalData=null;let auth;let functions;
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function message(value,error=false){$("#loginMessage").textContent=value;$("#loginMessage").style.color=error?"#ff8d8d":"#74e6b0"}
function phoneE164(value){const digits=String(value||"").replace(/\D/g,"");if(/^01[0125]\d{8}$/.test(digits))return `+2${digits}`;if(/^201[0125]\d{8}$/.test(digits))return `+${digits}`;throw new Error("اكتب رقم موبايل مصري صحيح");}
async function call(name,data={}){return(await httpsCallable(functions,name,{timeout:30000})(data)).data}
function bookingCard(item){return `<div><b>${esc(item.code)}</b><br>${esc((item.serviceNamesAr||[]).join(" + "))}<br><small>${esc(item.bookingDate||"")} ${esc(item.bookingTime||"")}</small></div>`}
function renderFavorite(){const id=$("#favoriteStaff").value;const item=portalData?.catalog?.staff?.find(value=>value.id===id);const target=$("#favoriteDetails");if(!item){target.hidden=true;$("#bookFavorite").hidden=true;return}target.hidden=false;target.innerHTML=`${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="${esc(item.nameAr)}" width="72" height="72">`:""}<div><b>${esc(item.nameAr)}</b><span>${esc(item.specialtyAr||"حلاق مزين مصر")}</span><small>${(item.branchIds||[]).map(value=>value==="talkha"?"فرع طلخا":value==="mashaya"?"فرع المشاية":value).join(" • ")}</small><small>المواعيد المتاحة تظهر بعد اختيار الخدمة والتاريخ.</small></div>`;$("#bookFavorite").hidden=false}
async function loadPortal(){portalData=await call("getCustomerPortal");const c=portalData.customer;$("#customerName").textContent=`${c.firstName||""} ${c.lastName||""}`.trim()||"عميل مزين مصر";$("#points").textContent=Number(c.pointsBalance||0);$("#cashback").textContent=`${Number(c.cashbackBalance||0).toFixed(2)} ج.م`;const visits=Number(c.bookingCount||portalData.bookingHistory?.length||0);const tiers=visits>=10?{name:"عميل مميز",from:10,to:20}:visits>=5?{name:"عميل دائم",from:5,to:10}:{name:"عضو مزين",from:0,to:5};const progress=Math.min(100,Math.round(((visits-tiers.from)/(tiers.to-tiers.from))*100));$("#memberTier").textContent=tiers.name;$("#tierProgressValue").textContent=`${progress}%`;$("#tierProgressBar").style.width=`${progress}%`;$("#tierProgressLabel").textContent=visits>=20?"وصلت لأعلى مستوى حاليًا":`متبقي ${Math.max(0,tiers.to-visits)} زيارة للمستوى التالي`;if(c.qrToken)await QRCode.toCanvas($("#customerQr"),c.qrToken,{width:220,margin:1,errorCorrectionLevel:"M"});$("#upcoming").innerHTML=portalData.upcomingBookings.map(bookingCard).join("")||"<div>لا توجد حجوزات قادمة.</div>";$("#walletActivity").innerHTML=portalData.walletActivity.map(item=>`<div><b>${esc(item.type)}</b><br>${Number(item.points||0)} نقطة • ${Number(item.cashback||0).toFixed(2)} ج.م</div>`).join("")||"<div>لا توجد حركات بعد.</div>";if(portalData.lastBooking){$("#lastBooking").innerHTML=bookingCard(portalData.lastBooking);$("#repeatBooking").hidden=false}const catalog=await call("getCatalog");portalData.catalog=catalog;$("#favoriteStaff").innerHTML='<option value="">اختر الحلاق</option>'+catalog.staff.map(item=>`<option value="${esc(item.id)}" ${item.id===c.favoriteStaffId?"selected":""}>${esc(item.nameAr)} • ${esc(item.specialtyAr||"")}</option>`).join("");renderFavorite();$("#loginCard").hidden=true;$("#portal").hidden=false;$("#logout").hidden=false}
if(!configured){message("إعداد Firebase غير مكتمل.",true)}else{const app=initializeApp(config);if(globalThis.__APP_CHECK_SITE_KEY__)initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(globalThis.__APP_CHECK_SITE_KEY__),isTokenAutoRefreshEnabled:true});auth=getAuth(app);functions=getFunctions(app,"europe-west1");setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,user=>{if(user)loadPortal().catch(error=>message(error.message,true));else{$("#loginCard").hidden=false;$("#portal").hidden=true;$("#logout").hidden=true}})}
$("#phoneForm").addEventListener("submit",async event=>{event.preventDefault();const button=$("#sendCode");button.disabled=true;try{globalThis.recaptchaVerifier ||= new RecaptchaVerifier(auth,"recaptcha",{size:"normal"});confirmation=await signInWithPhoneNumber(auth,phoneE164($("#phone").value),globalThis.recaptchaVerifier);$("#phoneForm").hidden=true;$("#codeForm").hidden=false;message("تم إرسال رمز التحقق.")}catch(error){message(error.message||"تعذر إرسال الرمز",true);globalThis.recaptchaVerifier?.clear();globalThis.recaptchaVerifier=null}finally{button.disabled=false}});
$("#codeForm").addEventListener("submit",async event=>{event.preventDefault();const button=$("#verifyCode");button.disabled=true;try{await confirmation.confirm($("#code").value.trim());message("تم تسجيل الدخول.")}catch{message("رمز التحقق غير صحيح أو انتهت صلاحيته.",true)}finally{button.disabled=false}});
$("#logout").addEventListener("click",()=>signOut(auth));$("#saveFavorite").addEventListener("click",async()=>{const staffId=$("#favoriteStaff").value;if(!staffId)return;$("#saveFavorite").disabled=true;try{await call("saveFavoriteBarber",{staffId});message("تم حفظ الحلاق المفضل.")}catch(error){message(error.message,true)}finally{$("#saveFavorite").disabled=false}});$("#repeatBooking").addEventListener("click",()=>{const last=portalData?.lastBooking;if(!last)return;sessionStorage.setItem("mz-repeat-booking",JSON.stringify({branchId:last.branchId,staffId:last.staffId,items:(last.items||[]).map(item=>({id:item.id,kind:item.kind,qty:item.qty||1}))}));location.href="/?repeat=1#services"});
$("#favoriteStaff").addEventListener("change",renderFavorite);$("#bookFavorite").addEventListener("click",()=>{const worker=portalData?.catalog?.staff?.find(item=>item.id===$("#favoriteStaff").value);if(!worker)return;sessionStorage.setItem("mz-favorite-booking",JSON.stringify({staffId:worker.id,branchId:portalData.customer.lastBranchId||(worker.branchIds||[])[0]||"talkha"}));location.href="/?favorite=1#services"});
